{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
data:
  DATABASE_URL: postgresql://datahq:123456@postgres/datahub
  EXTERNAL_ADDRESS: {{ default "api.datahub.io" | quote }}
  GUNICORN_PORT: "8000"
{{ end }}
