language: bash
sudo: required
env:
  global:
    - GIT_PR_BODDY_MESSAGE="Please visit https://datahub.io and make sure everything works as expected!"
    - GIT_PRODUCTION_BRANCH=production
    - GIT_HEAD=master
services:
  - docker
install:
  - curl -L https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | sudo bash
script:
  - bash helm_lint_all.sh
deploy:
  -
    provider: script
    script: bash .travis_deploy.sh datahub-testing && bash apps_travis_script.sh pr
    on:
      branch: master
  -
    provider: script
    script: bash .travis_deploy.sh datahub-production
    on:
      branch: production



{
  "url": "https://api.github.com/repos/datahq/deploy/pulls/66",
  "id": 190881852,
  "html_url": "https://github.com/datahq/deploy/pull/66",
  "diff_url": "https://github.com/datahq/deploy/pull/66.diff",
  "patch_url": "https://github.com/datahq/deploy/pull/66.patch",
  "issue_url": "https://api.github.com/repos/datahq/deploy/issues/66",
  "number": 66,
  "state": "open",
  "locked": false,
  "title": "test PR",
  "user": {
    "login": "datopianbot",
    "id": 27331587,
    "avatar_url": "https://avatars2.githubusercontent.com/u/27331587?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/datopianbot",
    "html_url": "https://github.com/datopianbot",
    "followers_url": "https://api.github.com/users/datopianbot/followers",
    "following_url": "https://api.github.com/users/datopianbot/following{/other_user}",
    "gists_url": "https://api.github.com/users/datopianbot/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/datopianbot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/datopianbot/subscriptions",
    "organizations_url": "https://api.github.com/users/datopianbot/orgs",
    "repos_url": "https://api.github.com/users/datopianbot/repos",
    "events_url": "https://api.github.com/users/datopianbot/events{/privacy}",
    "received_events_url": "https://api.github.com/users/datopianbot/received_events",
    "type": "User",
    "site_admin": false
  },
  "body": "Please visit https://datahub.io and make sure everything works as expected!",
  "created_at": "2018-05-28T09:30:37Z",
  "updated_at": "2018-05-28T09:30:37Z",
  "closed_at": null,
  "merged_at": null,
  "merge_commit_sha": null,
  "assignee": null,
  "assignees": [

  ],
  "requested_reviewers": [

  ],
  "requested_teams": [

  ],
  "labels": [

  ],
  "milestone": null,
  "commits_url": "https://api.github.com/repos/datahq/deploy/pulls/66/commits",
  "review_comments_url": "https://api.github.com/repos/datahq/deploy/pulls/66/comments",
  "review_comment_url": "https://api.github.com/repos/datahq/deploy/pulls/comments{/number}",
  "comments_url": "https://api.github.com/repos/datahq/deploy/issues/66/comments",
  "statuses_url": "https://api.github.com/repos/datahq/deploy/statuses/a29da53d904f8627cc5ea64361b32eb6cb77b44a",
  "head": {
    "label": "datahq:master",
    "ref": "master",
    "sha": "a29da53d904f8627cc5ea64361b32eb6cb77b44a",
    "user": {
      "login": "datahq",
      "id": 29688219,
      "avatar_url": "https://avatars1.githubusercontent.com/u/29688219?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/datahq",
      "html_url": "https://github.com/datahq",
      "followers_url": "https://api.github.com/users/datahq/followers",
      "following_url": "https://api.github.com/users/datahq/following{/other_user}",
      "gists_url": "https://api.github.com/users/datahq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/datahq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/datahq/subscriptions",
      "organizations_url": "https://api.github.com/users/datahq/orgs",
      "repos_url": "https://api.github.com/users/datahq/repos",
      "events_url": "https://api.github.com/users/datahq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/datahq/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "repo": {
      "id": 96110954,
      "name": "deploy",
      "full_name": "datahq/deploy",
      "owner": {
        "login": "datahq",
        "id": 29688219,
        "avatar_url": "https://avatars1.githubusercontent.com/u/29688219?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/datahq",
        "html_url": "https://github.com/datahq",
        "followers_url": "https://api.github.com/users/datahq/followers",
        "following_url": "https://api.github.com/users/datahq/following{/other_user}",
        "gists_url": "https://api.github.com/users/datahq/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/datahq/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/datahq/subscriptions",
        "organizations_url": "https://api.github.com/users/datahq/orgs",
        "repos_url": "https://api.github.com/users/datahq/repos",
        "events_url": "https://api.github.com/users/datahq/events{/privacy}",
        "received_events_url": "https://api.github.com/users/datahq/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://github.com/datahq/deploy",
      "description": "Deployment automation for the DataHub",
      "fork": false,
      "url": "https://api.github.com/repos/datahq/deploy",
      "forks_url": "https://api.github.com/repos/datahq/deploy/forks",
      "keys_url": "https://api.github.com/repos/datahq/deploy/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/datahq/deploy/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/datahq/deploy/teams",
      "hooks_url": "https://api.github.com/repos/datahq/deploy/hooks",
      "issue_events_url": "https://api.github.com/repos/datahq/deploy/issues/events{/number}",
      "events_url": "https://api.github.com/repos/datahq/deploy/events",
      "assignees_url": "https://api.github.com/repos/datahq/deploy/assignees{/user}",
      "branches_url": "https://api.github.com/repos/datahq/deploy/branches{/branch}",
      "tags_url": "https://api.github.com/repos/datahq/deploy/tags",
      "blobs_url": "https://api.github.com/repos/datahq/deploy/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/datahq/deploy/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/datahq/deploy/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/datahq/deploy/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/datahq/deploy/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/datahq/deploy/languages",
      "stargazers_url": "https://api.github.com/repos/datahq/deploy/stargazers",
      "contributors_url": "https://api.github.com/repos/datahq/deploy/contributors",
      "subscribers_url": "https://api.github.com/repos/datahq/deploy/subscribers",
      "subscription_url": "https://api.github.com/repos/datahq/deploy/subscription",
      "commits_url": "https://api.github.com/repos/datahq/deploy/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/datahq/deploy/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/datahq/deploy/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/datahq/deploy/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/datahq/deploy/contents/{+path}",
      "compare_url": "https://api.github.com/repos/datahq/deploy/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/datahq/deploy/merges",
      "archive_url": "https://api.github.com/repos/datahq/deploy/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/datahq/deploy/downloads",
      "issues_url": "https://api.github.com/repos/datahq/deploy/issues{/number}",
      "pulls_url": "https://api.github.com/repos/datahq/deploy/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/datahq/deploy/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/datahq/deploy/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/datahq/deploy/labels{/name}",
      "releases_url": "https://api.github.com/repos/datahq/deploy/releases{/id}",
      "deployments_url": "https://api.github.com/repos/datahq/deploy/deployments",
      "created_at": "2017-07-03T12:57:08Z",
      "updated_at": "2018-05-28T09:17:44Z",
      "pushed_at": "2018-05-28T09:17:43Z",
      "git_url": "git://github.com/datahq/deploy.git",
      "ssh_url": "git@github.com:datahq/deploy.git",
      "clone_url": "https://github.com/datahq/deploy.git",
      "svn_url": "https://github.com/datahq/deploy",
      "homepage": "https://datahub.io/",
      "size": 234,
      "stargazers_count": 7,
      "watchers_count": 7,
      "language": "Shell",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 4,
      "mirror_url": null,
      "archived": false,
      "open_issues_count": 7,
      "license": null,
      "forks": 4,
      "open_issues": 7,
      "watchers": 7,
      "default_branch": "master"
    }
  },
  "base": {
    "label": "datahq:production",
    "ref": "production",
    "sha": "5bb6953fdb6f06b50fd795d0ab9a0e8bb0c8d285",
    "user": {
      "login": "datahq",
      "id": 29688219,
      "avatar_url": "https://avatars1.githubusercontent.com/u/29688219?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/datahq",
      "html_url": "https://github.com/datahq",
      "followers_url": "https://api.github.com/users/datahq/followers",
      "following_url": "https://api.github.com/users/datahq/following{/other_user}",
      "gists_url": "https://api.github.com/users/datahq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/datahq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/datahq/subscriptions",
      "organizations_url": "https://api.github.com/users/datahq/orgs",
      "repos_url": "https://api.github.com/users/datahq/repos",
      "events_url": "https://api.github.com/users/datahq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/datahq/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "repo": {
      "id": 96110954,
      "name": "deploy",
      "full_name": "datahq/deploy",
      "owner": {
        "login": "datahq",
        "id": 29688219,
        "avatar_url": "https://avatars1.githubusercontent.com/u/29688219?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/datahq",
        "html_url": "https://github.com/datahq",
        "followers_url": "https://api.github.com/users/datahq/followers",
        "following_url": "https://api.github.com/users/datahq/following{/other_user}",
        "gists_url": "https://api.github.com/users/datahq/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/datahq/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/datahq/subscriptions",
        "organizations_url": "https://api.github.com/users/datahq/orgs",
        "repos_url": "https://api.github.com/users/datahq/repos",
        "events_url": "https://api.github.com/users/datahq/events{/privacy}",
        "received_events_url": "https://api.github.com/users/datahq/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://github.com/datahq/deploy",
      "description": "Deployment automation for the DataHub",
      "fork": false,
      "url": "https://api.github.com/repos/datahq/deploy",
      "forks_url": "https://api.github.com/repos/datahq/deploy/forks",
      "keys_url": "https://api.github.com/repos/datahq/deploy/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/datahq/deploy/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/datahq/deploy/teams",
      "hooks_url": "https://api.github.com/repos/datahq/deploy/hooks",
      "issue_events_url": "https://api.github.com/repos/datahq/deploy/issues/events{/number}",
      "events_url": "https://api.github.com/repos/datahq/deploy/events",
      "assignees_url": "https://api.github.com/repos/datahq/deploy/assignees{/user}",
      "branches_url": "https://api.github.com/repos/datahq/deploy/branches{/branch}",
      "tags_url": "https://api.github.com/repos/datahq/deploy/tags",
      "blobs_url": "https://api.github.com/repos/datahq/deploy/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/datahq/deploy/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/datahq/deploy/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/datahq/deploy/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/datahq/deploy/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/datahq/deploy/languages",
      "stargazers_url": "https://api.github.com/repos/datahq/deploy/stargazers",
      "contributors_url": "https://api.github.com/repos/datahq/deploy/contributors",
      "subscribers_url": "https://api.github.com/repos/datahq/deploy/subscribers",
      "subscription_url": "https://api.github.com/repos/datahq/deploy/subscription",
      "commits_url": "https://api.github.com/repos/datahq/deploy/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/datahq/deploy/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/datahq/deploy/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/datahq/deploy/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/datahq/deploy/contents/{+path}",
      "compare_url": "https://api.github.com/repos/datahq/deploy/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/datahq/deploy/merges",
      "archive_url": "https://api.github.com/repos/datahq/deploy/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/datahq/deploy/downloads",
      "issues_url": "https://api.github.com/repos/datahq/deploy/issues{/number}",
      "pulls_url": "https://api.github.com/repos/datahq/deploy/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/datahq/deploy/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/datahq/deploy/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/datahq/deploy/labels{/name}",
      "releases_url": "https://api.github.com/repos/datahq/deploy/releases{/id}",
      "deployments_url": "https://api.github.com/repos/datahq/deploy/deployments",
      "created_at": "2017-07-03T12:57:08Z",
      "updated_at": "2018-05-28T09:17:44Z",
      "pushed_at": "2018-05-28T09:17:43Z",
      "git_url": "git://github.com/datahq/deploy.git",
      "ssh_url": "git@github.com:datahq/deploy.git",
      "clone_url": "https://github.com/datahq/deploy.git",
      "svn_url": "https://github.com/datahq/deploy",
      "homepage": "https://datahub.io/",
      "size": 234,
      "stargazers_count": 7,
      "watchers_count": 7,
      "language": "Shell",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 4,
      "mirror_url": null,
      "archived": false,
      "open_issues_count": 7,
      "license": null,
      "forks": 4,
      "open_issues": 7,
      "watchers": 7,
      "default_branch": "master"
    }
  },
  "_links": {
    "self": {
      "href": "https://api.github.com/repos/datahq/deploy/pulls/66"
    },
    "html": {
      "href": "https://github.com/datahq/deploy/pull/66"
    },
    "issue": {
      "href": "https://api.github.com/repos/datahq/deploy/issues/66"
    },
    "comments": {
      "href": "https://api.github.com/repos/datahq/deploy/issues/66/comments"
    },
    "review_comments": {
      "href": "https://api.github.com/repos/datahq/deploy/pulls/66/comments"
    },
    "review_comment": {
      "href": "https://api.github.com/repos/datahq/deploy/pulls/comments{/number}"
    },
    "commits": {
      "href": "https://api.github.com/repos/datahq/deploy/pulls/66/commits"
    },
    "statuses": {
      "href": "https://api.github.com/repos/datahq/deploy/statuses/a29da53d904f8627cc5ea64361b32eb6cb77b44a"
    }
  },
  "author_association": "MEMBER",
  "merged": false,
  "mergeable": null,
  "rebaseable": null,
  "mergeable_state": "unknown",
  "merged_by": null,
  "comments": 0,
  "review_comments": 0,
  "maintainer_can_modify": false,
  "commits": 17,
  "additions": 341,
  "deletions": 3,
  "changed_files": 7
}
