language: bash
sudo: required
env:
  global:
    - GIT_PR_BODDY_MESSAGE="Please visit https://datahub.io and make sure everything works as expected!"
    - GIT_PRODUCTION_BRANCH=production
    - GIT_HEAD=master
services:
  - docker
install:
  - curl -L https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | sudo bash
script:
  - bash helm_lint_all.sh
deploy:
  -
    provider: script
    script:
      - bash .travis_deploy.sh datahub-testing
      - bash apps_travis_script.sh pr
    on:
      branch: master
  -
    provider: script
    script: bash .travis_deploy.sh datahub-production
    on:
      branch: production
