auth:
  image: datopian/auth-datahub:d21d938492242adf1b6576910686c176001e041e
filemanager:
  image: datopian/filemanager:latest
frontend:
  image: datopian/datahub-frontend:4cf2c05cb067c6d3a2f16f9ca43d4c75e0573c38
metastore:
  image: datopian/metastore:latest
nginx:
  image: datopian/datahub-nginx:d21d938492242adf1b6576910686c176001e041e
plans:
  image: datopian/plans:latest
rawstore:
  image: datopian/bitstore:latest
resolver:
  image: datopian/resolver:latest
specstore:
  image: datopian/specstore:latest
