{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: specstore
spec:
  replicas: 1
  selector:
    matchLabels: {app: specstore}
  template:
    metadata:
      labels:
        app: specstore
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: specstore
        image: {{ .Values.image | default "datopian/specstore:latest" | quote }}
        ports:
        - containerPort: 8000
        resources: {{ .Values.resources }}
        envFrom:
        - configMapRef:
            name: specstore
        {{ if .Values.secretName }}
        # override the values from configmap
        - secretRef:
            name: {{ .Values.secretName | quote }}
        {{ end }}
{{ end }}
