{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      {{ if .Values.global.persistentDataVolume.hostname }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.global.persistentDataVolume.hostname | quote }}
      {{ end }}
      containers:
      - name: nginx
        image: {{ .Values.image | default "datopian/nginx:latest" | quote }}
        ports:
        - containerPort: 80
        - containerPort: 5601
        resources: {{ .Values.resources }}
        {{ if .Values.overrideStartupScript }}
        command:
        - sh
        - "-c"
        - |
          {{ .Values.overrideStartupScript }}
        {{ end }}
{{ end }}
