{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: plans
data:
  BASIC_AUTH_PASSWORD: datopian
  BASIC_AUTH_USERNAME: datopian
  SESSION_SECRET_KEY: datopian
  DATABASE_URL: postgresql://datahq:123456@postgres/datahub
{{ end }}
