{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plans
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plans
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: plans
        image: {{ .Values.image | default "datopian/plans:latest" | quote }}
        ports:
        - containerPort: 8000
        resources: {{ .Values.resources }}
        envFrom:
        - configMapRef:
            name: plans
        {{ if .Values.secretName }}
        # override the values from configmap
        - secretRef:
            name: {{ .Values.secretName | quote }}
        {{ end }}
{{ end }}
